service: ProfessorRank3 # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.6
  region: us-east-2
  timeout: 15
  vpc:
    securityGroupIds:
      - sg-d476d4bf
    subnetIds:
      - subnet-40cc293b
      - subnet-5caf6535
      - subnet-f4cbf0be



# you can overwrite defaults here
#  stage: dev

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

  environment:
    DB_NAME: professorrank
    DB_USER_NAME: professorrankadmin
    DB_PASSWORD: Coolmanfan101
    DB_HOST: professorrank-db.ckwf3bstuuoa.us-east-2.rds.amazonaws.com
    DB_PORT: 5432

# you can add packaging information here
#package:
  include:
    - db.py

functions:
  createProfessor:
    handler: handler.createProfessor
    events:
      - http:
          path: /professor
          method: post
  getProfessor:
    handler: handler.getProfessor
    events:
      - http:
          path: /professor/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
  createReview:
    handler: handler.createReview
    events:
      - http:
          path: /review/create
          method: post
  getReview:
    handler: handler.getReview
    events:
      - http:
          path: /review/{id}
          method: get
plugins:
  - serverless-python-requirements
custom:
    pythonRequirements:
      zip: true